// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

/* templ Card() {
	<p>Card</p>
}
*/
/* 	<div class="bio section p-10" id="bio">
	<div class="card lg:card-side bg-base-100 shadow-xl">
		<figure><img src="/public/profile.jpeg" alt="Your Name"/></figure>
		<div class="card-body">
			<h2 class="card-title">Your Name</h2>
			<p>Your professional bio here. Summarize your background, skills, and professional interests</p>
			<div class="card-actions justify-end">
				<button class="btn btn-primary">Contact Me</button>
			</div>
		</div>
	</div>
</div> */
