---
name: "Generate PDF"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - public/**
      - views/layout/pdf.templ
      - views/pdf_components/**
      - tailwind.pdf.css
      - tailwind.config.js
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write
  packages: write

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev
          sudo apt-get install -y libnss3
          sudo apt-get install -y libatk-bridge2.0-0
          sudo apt-get install -y libgtk-3-0
          sudo apt-get install -y libgbm1

      - name: Setup templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Generate the templates with templ
        run: |
          templ generate

      - name: Run Mage
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: GenerateCVAsPDF

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: cv.pdf
          retention-days: 1

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Release PDF
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          files: cv.pdf
          tag_name: cv-${{ steps.date.outputs.date }}
          name: CV Update ${{ steps.date.outputs.date }}
          body: Automated CV PDF update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
